#!/usr/bin/env python3
"""whose4.py -- how much of this disc was written for this disc, by two metrics.

`whose.py`, inherited from pc-harrypotter1-doc, runs here and gives 95.71 %,
but its tier rules name Epic's Unreal modules and a 10,000-sector hole that
does not exist on this disc, so the number it prints is right for the wrong
reasons. This restates the rule for this object and reports the answer twice:
by bytes and by file count. The two disagree violently, and the disagreement
is the finding.

THE RULE, stated so it can be argued with:

  tier 1  REDISTRIBUTED     a third party's product shipped whole: Microsoft's
                            DirectX installer and the Visual C++ 7.1 runtime.
  tier 2  PROTECTION        Macrovision's: DIAG.EXE and the two .TMP files at
                            the root. The SafeDisc wrapper around the game
                            executable is inside the zip and is not counted
                            separately, which understates this tier.
  tier 3  HELP RUNTIME      the RoboHelp WebHelp player: its JavaScript, its
                            skin GIFs and JPEGs, its icons, its stylesheets,
                            its applet jar and cab. Generated by a tool, not
                            written here. The .htm topic files are NOT in this
                            tier: their text is this publisher's.
  tier 4  PUBLISHER COMMON  Electronic Arts components that are the same on
                            every EA title of the period: the AutoRun shell,
                            the uninstaller, the electronic-registration tool
                            and its 19-language dictionary.
  tier 5  THIS PRODUCT      everything left.

Membership is decided by path and by name, and every file in tiers 1-4 is
printed so the rule can be checked file by file.

    python tools/whose4.py _work/iso
    python tools/whose4.py _work/iso --detail
"""
import argparse
import collections
import os
import sys

HELP_RUNTIME_EXT = {".js", ".gif", ".jpg", ".ico", ".css", ".jar", ".cab", ".lng", ".db"}
EA_COMMON = {
    "autorun.exe", "autorungui.dll", "eauninstall.exe",
    "ereg.exe", "easyinfo.exe", "ereg.bin", "ereg-dict.data",
    "easyreqs.xml", "config.xml",
}


def tier(rel, name):
    low = name.lower()
    p = rel.replace(chr(92), "/")
    if p.startswith("DirectX/"):
        return 1, "Microsoft DirectX redistributable"
    if low == "msvcr71.dll":
        return 1, "Microsoft Visual C++ 7.1 runtime"
    if low in ("diag.exe",):
        return 2, "Macrovision SafeDisc diagnostic"
    if low in ("00000001.tmp", "00000002.tmp"):
        return 2, "SafeDisc on-disc data"
    if p.startswith("Support/European Help Files/"):
        ext = os.path.splitext(low)[1]
        if ext in HELP_RUNTIME_EXT:
            return 3, "RoboHelp WebHelp runtime"
        return 5, "help topic text"
    if low.startswith("ereg-dict-") or low in EA_COMMON:
        return 4, "Electronic Arts common component"
    if low.endswith(".log") and p.startswith("Support/"):
        return 4, "Electronic Arts common component"
    return 5, "this product"


NAMES = {1: "REDISTRIBUTED", 2: "PROTECTION", 3: "HELP RUNTIME",
         4: "PUBLISHER COMMON", 5: "THIS PRODUCT"}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("root")
    ap.add_argument("--detail", action="store_true")
    a = ap.parse_args()

    rows = []
    for dp, dn, fn in os.walk(a.root):
        for f in fn:
            p = os.path.join(dp, f)
            rel = os.path.relpath(p, a.root).replace(chr(92), "/")
            t, why = tier(rel, f)
            rows.append((t, why, rel, os.path.getsize(p)))

    nfiles = len(rows)
    nbytes = sum(r[3] for r in rows)
    print("files : %d" % nfiles)
    print("bytes : %d" % nbytes)
    print()
    print("%-4s %-18s %8s %8s %16s %8s" % ("tier", "", "files", "% files", "bytes", "% bytes"))
    for t in sorted(NAMES):
        sel = [r for r in rows if r[0] == t]
        b = sum(r[3] for r in sel)
        print("%-4d %-18s %8d %7.2f%% %16d %7.2f%%"
              % (t, NAMES[t], len(sel), 100.0 * len(sel) / nfiles, b, 100.0 * b / nbytes))
    own = [r for r in rows if r[0] == 5]
    print()
    print("written for this disc, BY BYTES      : %.2f %%"
          % (100.0 * sum(r[3] for r in own) / nbytes))
    print("written for this disc, BY FILE COUNT : %.2f %%"
          % (100.0 * len(own) / nfiles))
    print()

    z = [r for r in rows if r[2] == "0compressed.zip"]
    if z:
        zb = z[0][3]
        print("sensitivity: one file, 0compressed.zip, is %d bytes = %.2f %% of the disc."
              % (zb, 100.0 * zb / nbytes))
        rest = nbytes - zb
        own_rest = sum(r[3] for r in own) - zb
        print("with that one file removed from both sides, the by-bytes figure is %.2f %%"
              % (100.0 * own_rest / rest))
        print("so the headline number is decided by a single membership call.")
    print()

    print("by reason:")
    agg = collections.defaultdict(lambda: [0, 0])
    for t, why, rel, b in rows:
        agg[(t, why)][0] += 1
        agg[(t, why)][1] += b
    for (t, why), (c, b) in sorted(agg.items()):
        print("  %d  %-38s %6d %16d" % (t, why, c, b))

    if a.detail:
        print()
        for t in (1, 2, 3, 4):
            sel = sorted([r for r in rows if r[0] == t], key=lambda r: -r[3])
            print("  tier %d  %s  (%d files)" % (t, NAMES[t], len(sel)))
            for _, why, rel, b in sel[:40]:
                print("     %12d  %s" % (b, rel))
            if len(sel) > 40:
                print("     ... %d more" % (len(sel) - 40))
            print()


if __name__ == "__main__":
    main()
